tweak pipelines

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,6 +34,14 @@ jobs:
           cd "01-ecr" 
           echo "NOTE: Building ECR Instance."
 
+          # Prevent a mess for happening if you run the github action without a backend
+
+          backend=$(grep -r 'backend ' *.tf 2> /dev/null)
+          if [ -z "$backend" ]; then
+              echo "ERROR: No terraform backend configuration is defined."
+              #exit 1
+          fi
+
           # Initialize Terraform in the directory.
           terraform init
 
@@ -101,6 +109,14 @@ jobs:
             cd 03-apprunner
             echo "NOTE: Building apprunner instance and deploy flask container."
 
+            # Prevent a mess for happening if you run the github action without a backend
+
+            backend=$(grep -r 'backend ' *.tf 2> /dev/null)
+            if [ -z "$backend" ]; then
+              echo "ERROR: No terraform backend configuration is defined."
+              #exit 1
+            fi
+            
             # Initialize Terraform in the directory.
             terraform init
 
diff --git a/.github/workflows/checkenv.yml b/.github/workflows/checkenv.yml
--- a/.github/workflows/checkenv.yml
+++ b/.github/workflows/checkenv.yml
@@ -50,16 +50,17 @@ jobs:
             # If all variables are set, print success message
             echo "NOTE: All required environment variables are set."
 
-            # List of required files
-            REQUIRED_FILES=("./01-ecr/01-ecr-backend.tf" "./03-apprunner/03-apprunner-backend.tf")
+            backend=$(grep -r 'backend ' ./01-ecr/*.tf 2> /dev/null)
+            if [ -z "$backend" ]; then
+              echo "ERROR: No terraform backend configuration is defined for 01-ecr."
+              exit 1
+            fi
 
-            # Check if required files exist
-            for FILE in "${REQUIRED_FILES[@]}"; do
-              if [ ! -f "$FILE" ]; then
-                  echo "ERROR: Required file '$FILE' does not exist."
-              exit -1
-              fi
-            done
+            backend=$(grep -r 'backend ' ./03-apprunner/*.tf 2> /dev/null)
+            if [ -z "$backend" ]; then
+              echo "ERROR: No terraform backend configuration is defined for 03-apprunner."
+              exit 1
+            fi
 
             # If all checks pass
             echo "NOTE: All required backend files exist."
