tweak checkenv

diff --git a/.github/workflows/checkenv.yml b/.github/workflows/checkenv.yml
--- a/.github/workflows/checkenv.yml
+++ b/.github/workflows/checkenv.yml
@@ -54,14 +54,14 @@ jobs:
             
             backend=$(grep -r 'backend ' ./01-ecr/*.tf 2> /dev/null)
             if [ -z "$backend" ]; then
-              printf "No terraform backend configuration is defined for 01-ecr."
-              exit 1
+              echo "ERROR: No terraform backend configuration is defined for 01-ecr."
+              #exit 1
             fi
 
             backend=$(grep -r 'backend ' ./03-apprunner/*.tf 2> /dev/null)
             if [ -z "$backend" ]; then
-              printf "No terraform backend configuration is defined for 03-apprunner."
-              exit 1
+              echo "ERROR: No terraform backend configuration is defined for 03-apprunner."
+              #exit 1
             fi
 
             # If all checks pass
